// 네트워크 주소
export const BLOCK_CHAIN_ENDPOINT = 'https://api.baobab.klaytn.net:8651'
// 스마트 컨트랙트 주소
export const USER_DID_REGISTRY_CONTRACT_ADDRESS = '0x21345BD3C27EB6f7b15D83ABD24D9B6683A641FF'

export const REAL_ESTATE_DID_REGISTRY_CONTRACT_ADDRESS = ''

export const CITIZENSHIP_VC_REGISTRY_CONTRACT_ADDRESS = ''

export const OWNERSHIP_VC_REGISTRY_CONTRACT_ADDRESS = ''