spring:
  application:
    name: chattings
  config:
    import:
      - classpath:/keys.yml
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host:localhost:3306}/block-homes?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${db.username}
    password: ${db.password}

server:
  port: 8081
#  servlet:
#    context-path: /chat

logging:
  level:
    org:
      hibernate:
        SQL: debug
